version: "3.4"

services:
  lab_management:
    container_name: lab_management
    build: lab_app

    ports:
      - 3001:3001
    volumes:
      - ../lab_management:/usr/local/lab_management/

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
